"""Simulated annealing algorithms for pseudo-boolean optimization.

This module implements simulated annealing (SA), a probabilistic local search
algorithm that accepts worsening moves with a temperature-dependent probability.
This allows escape from local optima early in the search, while gradually
converging to hill-climbing behavior as the temperature decreases.

Cooling schedules control the temperature decay over time:
    - **Logarithmic**: T(t) = d / log(t + 1), theoretically optimal but slow.
    - **Exponential**: T(t) = T0 * alpha^t, fast decay, commonly used.
    - **Linear**: T(t) = T0 - (T0 - Tf) * t / max_iter, bounded descent.

Classes:
    CoolingSchedule: Protocol for temperature schedules.
    SimulatedAnnealing: Main SA algorithm with configurable cooling.
    LogarithmicCooling: Logarithmic temperature decay.
    ExponentialCooling: Exponential temperature decay.
    LinearCooling: Linear temperature decay with minimum bound.
"""

from collections.abc import Callable
from dataclasses import dataclass
from typing import Protocol

import numpy as np

from regret.core.base import Algorithm, Problem


class CoolingSchedule(Protocol):
    """Protocol for temperature schedules used by simulated annealing.

    Cooling schedules are callable objects that map evaluation indices to
    temperature values. The temperature controls the acceptance probability
    of worsening moves in the Metropolis criterion.
    """

    def __call__(self, t: int) -> int | float:
        """Return a temperature value for the given evaluation index.

        Args:
            t: Evaluation index.

        Returns:
            Temperature value at evaluation index t.
        """
        ...


class SimulatedAnnealing(Algorithm):
    """Simulated Annealing with configurable cooling schedule.

    Implements the Metropolis-Hastings algorithm adapted for maximization
    problems. At each step, a random neighbor is generated by flipping one
    bit. The neighbor is always accepted if it improves fitness; otherwise,
    it is accepted with probability exp(delta/T) where delta is the fitness
    difference and T is the current temperature.

    Attributes:
        T_func: Cooling schedule callable that maps evaluation index to temperature.
        min_T: Minimum temperature clamp to avoid numerical issues.
        current: Binary array representing the current candidate solution.
        current_value: Fitness value of the current solution.
    """

    def __init__(
        self,
        problem: Problem,
        T_func: CoolingSchedule | None = None,
        min_T: float | None = None,
        seed: int | None = None,
        callback: Callable[[int, float, float, np.ndarray], None] | None = None,
    ):
        """Initialize simulated annealing with a cooling schedule.

        Args:
            problem: Problem to optimize.
            T_func: Temperature schedule callable; defaults to logarithmic.
            min_T: Minimum temperature clamp to avoid zero temperature.
            seed: Optional RNG seed for reproducibility.
            callback: Optional callback invoked at each step.
        """
        self.T_func = T_func or LogarithmicCooling()
        self.min_T = min_T or 1e-9
        super().__init__(problem, seed, callback)

    def reset(self):
        """Reinitialize state, solution, and trajectory for a fresh run."""
        super().reset()
        self.current = self.rng.integers(0, 2, size=self.problem.n)
        self.current_value = self.problem.evaluate(self.current)
        self.evaluations = 1
        self.best_value = self.current_value
        self.best_solution = self.current.copy()
        self._record_history(self.current_value, self.current)

    def step(self):
        """Perform one Metropolis update using the configured cooling schedule.

        Temperature is clamped to min_T to avoid numerical issues with zero temperature.
        Once temperature reaches min_T, SA behaves like a greedy hill-climber that only
        accepts improving moves. While early stopping at this point could save evaluations,
        continuing allows the algorithm to potentially escape via the min_T acceptance
        probability (exp(delta/min_T) for small negative delta). The current implementation
        continues until the budget is exhausted for consistency with other algorithms.
        """
        # Generate neighbor
        neighbor = self.current.copy()
        i = self.rng.integers(0, self.problem.n)
        neighbor[i] = 1 - neighbor[i]

        neighbor_value = self.problem.evaluate(neighbor)

        # NOTE: Capping down at a minimum temperature
        # Temperature is clamped at min_T to maintain numerical stability.
        # At min_T, acceptance probability for worsening moves is very low but non-zero.
        T = max(self.min_T, self.T_func(self.evaluations))
        # Since evals = 1 initially, due to the reset,
        # incremented after temperature calculation to avoid one-off deviation
        self.evaluations += 1
        delta = neighbor_value - self.current_value

        # Metropolis acceptance criterion
        # NOTE: Original Metropolis acceptance uses exp(-delta/T), for minimisation problems
        # Here, we use exp(delta/T), since we use maximisation problems
        if delta >= 0 or self.rng.random() < np.exp(delta / T):
            self.current = neighbor
            self.current_value = neighbor_value

        if self.current_value > self.best_value:
            self.best_value = self.current_value
            self.best_solution = self.current.copy()

        self._record_history(self.current_value, self.current)


@dataclass(frozen=True)
class LogarithmicCooling(CoolingSchedule):
    """Logarithmic cooling schedule: T(t) = d / log(t + 1).

    Provides slow, theoretically optimal cooling that guarantees convergence
    to the global optimum given infinite time. In practice, convergence is
    often too slow for fixed-budget optimization.

    Attributes:
        d: Scaling constant for temperature decay (default: 1.0).
    """

    d: float = 1.0

    def __call__(self, t: int) -> int | float:
        """Return logarithmic temperature at evaluation index t.

        Args:
            t: Evaluation index.

        Returns:
            Temperature value d / log(t + 1).
        """
        return self.d / np.log(t + 1)


@dataclass(frozen=True)
class ExponentialCooling(CoolingSchedule):
    """Exponential cooling schedule: T(t) = T0 * alpha^t.

    Provides fast geometric decay commonly used in practice. The parameter
    alpha controls the decay rate; typical values are 0.9 to 0.99.

    Attributes:
        T0: Initial temperature (default: 1.0).
        alpha: Decay factor per evaluation, must be in (0, 1) (default: 0.95).
    """

    T0: float = 1.0
    alpha: float = 0.95

    def __call__(self, t: int) -> int | float:
        """Return exponentially decayed temperature at evaluation index t.

        Args:
            t: Evaluation index.

        Returns:
            Temperature value T0 * alpha**t.
        """
        return self.T0 * (self.alpha**t)


@dataclass(frozen=True)
class LinearCooling(CoolingSchedule):
    """Linear cooling schedule: T(t) = max(Tf, T0 - (T0 - Tf) * t / max_iter).

    Provides predictable linear decay from T0 to Tf over max_iter evaluations.
    Temperature is clamped at Tf to prevent negative values.

    Attributes:
        T0: Initial temperature (default: 1.0).
        Tf: Final minimum temperature (default: 0.01).
        max_iter: Number of iterations over which to decay (default: 10000).
    """

    T0: float = 1.0
    Tf: float = 0.01
    max_iter: int = 10000

    def __call__(self, t: int) -> int | float:
        """Return linearly decayed temperature at evaluation index t.

        Args:
            t: Evaluation index.

        Returns:
            Temperature value clipped to not fall below Tf.
        """
        return max(self.Tf, self.T0 - (self.T0 - self.Tf) * t / self.max_iter)
